### ISSUE TITLE
Where are you

### ISSUE THREAD

**Issue by allFictionAS** [sdhEmily/RobloxPatcher#1]
You just vanished into thin air without warning whats going on

**Comment by sdhEmily** [comment]
im back

**Comment by allFictionAS** [comment]
pog. this project is probably now long irrelevant because of all the server sided changes roblox is making to the client (fastflags, modding etc). There are still alot of issues as of this message with modding that need addressing. i just guessed you didn't care no more cause you archived the repo

**Comment by sdhEmily** [comment]
nah it still works flawlessly, fflags and mods

**Comment by allFictionAS** [comment]
i didnt notice until i checked the repo lol mb. also did you delete your discord lol thats why i said you 'vanished'

**Comment by sdhEmily** [comment]
i didnt delete my discord it got deactivated and i archived this since i didnt have macos anymore but i went to use this again and it was broken so i repaired it
